spring:
  profiles:
    active: ["db", "swagger"]
openai:
  api-key: "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"
  api-url: "https://api.openai.com/v1"
